apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: worker:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /worker
    git:
      ref: master
      uri: https://github.com/mmumshad/example-voting-app.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - generic:
      secret: db530f8da2b5815f
    type: Generic
  - github:
      secret: efa482497d6ce4f1
    type: GitHub
  - type: ConfigChange
status:
  lastVersion: 0
