apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: "{.data['database-password']}"
  name: db
stringData:
  database-name: db
  database-password: postgres_password
  database-user: postgres_user
